import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Eco-Home Services",
  description: "Generated by create next app",
};

const hubspotTrackingId = process.env.NEXT_PUBLIC_HUBSPOT_TRACKING_ID ?? "343410852";

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}`}
    >
      <body>
        {children}
        <Script
          id="hubspot-tracking"
          src={`https://js-na3.hs-scripts.com/${hubspotTrackingId}.js`}
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
